---
- name: Configure discoverable Bluetooth and device name
  ini_file:
    path: /etc/bluetooth/main.conf
    section: General
    option: '{{item.key}}'
    value: '{{item.value}}'
  loop:
    - key: Class
      value: '0x41C'
    - key: DiscoverableTimeout
      value: 0
    - key: Name
      value: 'Blue{{assigned_hostname[0]|upper}}{{assigned_hostname[1:]|lower}}'

- name: Disable hostname plugin of bluetoothd (allow manual name set)
  ini_file:
    path: /lib/systemd/system/bluetooth.service
    section: Service
    option: ExecStart
    value: /usr/lib/bluetooth/bluetoothd --noplugin=hostname

- name: Enable A2DP sink mode in bluealsa
  ini_file:
    path: /lib/systemd/system/bluealsa.service
    section: Service
    option: ExecStart
    value: /usr/bin/bluealsa -p a2dp-sink

- name: Install a2dp-agent
  copy: src=a2dp-agent dest=/usr/local/bin/a2dp-agent mode=0755

- name: Install bt-agent-a2dp service
  copy: src=bt-agent-a2dp.service dest=/etc/systemd/system/bt-agent-a2dp.service mode=0644

- name: Install a2dp-playback service
  template: src=a2dp-playback.service.j2 dest=/etc/systemd/system/a2dp-playback.service mode=0644

- name: Reload systemd settings
  systemd:
    daemon_reload: yes

- name: Start the Bluetooth audio services
  systemd:
    name: '{{item}}'
    state: started
    enabled: yes
  loop:
    - bt-agent-a2dp
    - a2dp-playback
