---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Create SSH directory for user ubuntu
    become_user: ubuntu
    file: state=directory path=/home/ubuntu/.ssh mode=0755

  - name: Install SSH key for user ubuntu
    become_user: ubuntu
    copy: content={{ssh_key.public}} dest=/home/ubuntu/.ssh/authorized_keys mode=0444

    # - name: Lock password for user pi
    #   user: name=pi password_lock=yes
