---
- hosts: all
  become: yes
  vars:
    network:
      ethernet:
        device: eth0
        address: 192.168.203.1/24
        dhcp:
          subnet: '192.168.203.0'
          mask: '255.255.255.0'
          range:
            low: '192.168.203.30'
            high: '192.168.203.200'
            dns:
            - '1.1.1.1'
            - '8.8.8.8'
            - '8.8.4.4'
            - '9.9.9.9'
      wifi:
        device: wlan0
  roles:
    - role: packages
    - role: ipv6
    - role: network
    - role: readonly
