---
- name: Check if Ookla repository is already configured
  raw: |
    grep -iR ookla /etc/apt/
  register: grep_ookla_result
  failed_when: false
  changed_when: false

- name: Configure Ookla speedtest repository if needed
  when: grep_ookla_result.rc != 0
  raw: |
    cd / &&
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash

- name: Update list of packages
  apt: cache_valid_time=43200 update_cache=yes

- name: Remove unneeded packages
  apt:
    state: absent
    name:
      # this one can occasionally make startup/shutdown very slow
      - unattended-upgrades

- name: Install base packages
  apt:
    state: present
    name:
      - openvpn
      - wireguard
      - isc-dhcp-server
      - iptables
      - speedometer
      - jq
      - screen
      # for darkstat
      - libpcap-dev
      - zlib1g-dev
      - autoconf
      # for captive portals
      - lynx
      # for when local access is not possible
      - tmate
      - dnsmasq
      # for having nslookup for testing
      - dnsutils
      # from Ookla's repo
      - speedtest

- name: Check if darkstat is installed
  stat: path=/usr/local/sbin/darkstat
  register: stat_darkstat

- name: Install darkstat
  when: not stat_darkstat.stat.exists
  raw: |
    cd / &&
    curl -L -o /tmp/darkstat.tar.gz https://github.com/emikulic/darkstat/archive/refs/tags/3.0.721.tar.gz &&
    rm -rf /tmp/darkstat &&
    mkdir /tmp/darkstat &&
    cd /tmp/darkstat &&
    tar xzf /tmp/darkstat.tar.gz &&
    cd darkstat* &&
    autoreconf -ivf &&
    ./configure --prefix=/usr/local &&
    make &&
    make install &&
    cd / &&
    rm -rf /tmp/darkstat /tmp/darkstat.tar.gz
