---
- name: Update list of packages
  apt: cache_valid_time=43200 update_cache=yes

- name: Install base packages
  apt:
    state: present
    name:
      - vim-nox
      - avahi-daemon
      - build-essential
      - git
      - autoconf
      - automake
      - xmltoman
      - libtool
      - libdaemon-dev
      - libpopt-dev
      - libconfig-dev
      - libasound2-dev
      - libpulse-dev
      - libavahi-client-dev
      - libssl-dev
      - libsoxr-dev
      - bluealsa
      - python-dbus
      - chrony
