---
- name: Update list of packages
  apt: cache_valid_time=43200 update_cache=yes

- name: Install base packages
  apt:
    state: present
    name:
      - openvpn
      - isc-dhcp-server
      - iptables
      - speedometer
      - jq
      - screen
