---
- name: starthere
  debug: msg=nope

- name: Create cache directory
  file: state=directory path=/var/cache/repos

- name: Clone shairport-sync
  git:
    repo: https://github.com/mikebrady/shairport-sync
    dest: /var/cache/repos/shairport-sync
    version: "{{shairport_sync_ver}}"
  register: shairport_git_status

- name: Sync shairport-sync to build dir
  command: 
    argv:
      - rsync
      - "-a"
      - "--delete"
      - "--cvs-exclude"
      - /var/cache/repos/shairport-sync/
      - /tmp/shairport-sync-build/
  when: shairport_git_status.changed

- name: Configure build for shairport-sync
  shell:
    chdir: /tmp/shairport-sync-build
    cmd: autoreconf -ifv && ./configure --sysconfdir=/etc --with-alsa --with-pa --with-pipe --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd
  when: shairport_git_status.changed

- name: Make shairport-sync and install it
  shell:
    chdir: /tmp/shairport-sync-build
    cmd: make && make install
  when: shairport_git_status.changed

- name: Remove intermediate artifacts for shairport-sync
  file: state=absent path=/tmp/shairport-sync-build

- name: Configure shairport-sync
  template: src=shairport-sync.conf.j2 dest=/etc/shairport-sync.conf mode=0644
  register: shairport_conf

- name: Enable shairport-sync service
  systemd:
    name: shairport-sync
    enabled: yes
    state: "{{'restarted' if shairport_conf.changed else 'started'}}"
