---
- name: starthere
  debug: msg={{telegram}}

- name: Add utility to notify through a Telegram channel
  template: src=telegram-notificator.py.j2 dest=/usr/local/bin/telegram-notificator mode=0711
