---
- name: Check if swapfile is enabled
  command:
    argv:
      - grep
      - -q
      - /swapfile
      - --
      - /proc/swaps
  register: grep_swapfile_status
  failed_when: False
  changed_when: "grep_swapfile_status.rc == 0"

- name: Disable swap
  command:
    argv:
      - "swapoff"
      - "--all"
  when: "grep_swapfile_status.rc == 0"
  changed_when: True

- name: Mask systemd unit generating swapfile
  systemd: name=swapfile.swap state=stopped masked=yes daemon_reload=yes

# Note: Ubuntu 22.04 keeps recreating it?!?!
- name: Remove swapfile
  file: state=absent path=/swapfile

- name: Add the Busybox in-memory logger
  apt: state=present name=busybox-syslogd

- name: Remove traditional logger
  apt: state=absent autoremove=yes purge=yes name=rsyslog
# Mega big kudos to https://medium.com/swlh/make-your-raspberry-pi-file-system-read-only-raspbian-buster-c558694de79

# - name: Remove unnecessary packages
#   apt:
#     state: absent
#     autoremove: yes
#     name:
#       - triggerhappy
#       - logrotate
#       - dphys-swapfile

# - name: Add the Busybox in-memory logger
#   apt: state=present name=busybox-syslogd

# - name: Remove traditional logger
#   apt: state=absent autoremove=yes purge=yes name=rsyslog

# - name: Check for noswap in kernel boot command
#   command:
#     argv:
#       - grep
#       - -q
#       - noswap
#       - --
#       - /boot/cmdline.txt
#   register: grep_noswap_status
#   failed_when: False
#   changed_when: 'grep_noswap_status.rc != 0'

# - name: Add noswap to kernel boot command
#   command:
#     argv:
#       - sed
#       - -i
#       - -e
#       - 's/^\(.*\)$/\1 fastboot noswap ro/g'
#       - --
#       - /boot/cmdline.txt
#   when: 'grep_noswap_status.rc != 0'
#   changed_when: True

- name: Check for ro (readonly) option in fstab
  command:
    argv:
      - grep
      - -q
      - ",ro"
      - --
      - /etc/fstab
  register: fstab_ro_status
  failed_when: False
  changed_when: "fstab_ro_status.rc != 0"

- name: Change root and boot to read-only without remounting
  command:
    argv:
      - sed
      - -i
      - -e
      - 's/\(\(ext4\)\s\+defaults\)/\1,ro/g'
      - --
      - /etc/fstab
  when: "fstab_ro_status.rc != 0"
  changed_when: True

- name: Add temp filesystem entries and mount
  mount:
    state: mounted
    src: tmpfs
    fstype: tmpfs
    path: "{{item}}"
    opts: nosuid,nodev
  loop:
    - /tmp
    - /var/log
    - /var/tmp
    - /var/lib/dhcp
    - /var/spool
    - /var/cache

- name: Copy netplan configuration directory to /var/tmp/etc_netplan
  command:
    argv:
      - rsync
      - -av
      - --delete
      - /etc/netplan/
      - /var/tmp/etc_netplan/

- name: Remove original netplan directory
  command:
    argv:
      - rm
      - -rf
      - /etc/netplan

- name: Replace /etc/netplan with a symlink to /var/tmp/etc_netplan
  command:
    argv:
      - ln
      - -sfn
      - /var/tmp/etc_netplan
      - /etc/netplan

- name: Fix mount permissions on tmp directories
  file: state=directory mode=1777 path="{{item}}"
  loop:
    - /tmp
    - /var/tmp
