---
- name: Assign hostname {{assigned_hostname}}
  hostname: name="{{assigned_hostname}}"

- name: Change hostname in /etc/hosts
  lineinfile:
    regexp: '^127\.0\.1\.1'
    state: present
    line: '127.0.1.1 {{assigned_hostname}}'
    path: /etc/hosts

- name: Enable avahi service
  systemd:
    name: avahi-daemon
    enabled: yes
    state: started

- name: Enable SSH advertisement
  copy:
    src: ssh.service
    dest: /etc/avahi/services/ssh.service
    mode: 0644
