---
- name: Disable systemd time synchronization daemon
  systemd:
    name: systemd-timesyncd
    enabled: no
    state: stopped

- name: Enable Chrony
  systemd:
    name: chrony
    enabled: yes
    state: started
