---
- name: Add gists updater
  copy: src=gistsupdater.sh dest=/usr/bin/gistsupdater mode=0755
  tags:
  - gists_setup

- name: Save vault password to the right place
  copy:
    dest: /home/pi/.ansible_vault_password
    mode: '0400'
    content: "{{ansible_vault_password}}"
    owner: pi
    group: pi
  tags:
  - gists_setup

- name: Run gists updater every minute
  cron:
    name: Run gists updater every minute
    minute: "*"
    job: "/usr/bin/gistsupdater > /dev/null 2> /dev/null || true"
    cron_file: "/etc/cron.d/gistsupdater"
    user: pi
  tags:
  - gists_setup

# Tag the following tasks with `gists` to make sure they get updated automatically

- name: Create the file
  copy:
    dest: /tmp/dummy  # specify the path where you want to create the file
    mode: '0644'
    content: "dummy"
    owner: pi
    group: pi
  tags:
  - gists

- meta: flush_handlers
